import { describe, expect, it } from 'bun:test';
import { solveFirst, solveSecond } from './index.ts';

describe('2025-07', () => {
  const testInput = `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`;
  it('first', () => {
    expect(solveFirst(testInput)).toBe(21);
  });
  it('second', () => {
    expect(solveSecond(testInput)).toBe(40);
  });
});
